# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, next]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - run: npm ci

      - name: Typecheck + lint
        run: npm test

      # Runs a set of commands using the runners shell
      - name: Publish unlisted addon to AMO
        env:
          FIREFOX_BETA_ID: ${{ secrets.FIREFOX_BETA_ID }}
          AMO_API_KEY: ${{ secrets.AMO_API_KEY }}
          AMO_API_SECRET: ${{ secrets.AMO_API_SECRET }}
          NIGHTLY_DISCORD_WEBHOOK_TOKEN: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK_TOKEN }}
          NIGHTLY_DISCORD_WEBHOOK_ID: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK_ID }}
          NIGHTLY_DISCORD_ROLE_ID: ${{ secrets.NIGHTLY_DISCORD_ROLE_ID }}
          NIGHTLY_TENOR_API_KEY: ${{ secrets.NIGHTLY_TENOR_API_KEY }}
          NIGHTLY_GIPHY_API_KEY: ${{ secrets.NIGHTLY_GIPHY_API_KEY }}
        run: npm run build:firefox-beta && npx web-ext sign --api-key="$AMO_API_KEY" --api-secret="$AMO_API_SECRET" -s dist --channel unlisted && npm run ts-node -- tools/uploadNightly.ts
